//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDV
    {
        public int ID_DichVu { get; set; }
        public int ID_PhieuKham { get; set; }
        public string KetQua { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual PhieuKham PhieuKham { get; set; }
    }
}
