//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenMon
    {
        public int ID_NhanVien { get; set; }
        public string ChuyenKhoa { get; set; }
        public string ChucDanh { get; set; }
        public string ThongTin { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
