//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuKham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuKham()
        {
            this.ChiTietDVs = new HashSet<ChiTietDV>();
            this.ChiTietToaThuocs = new HashSet<ChiTietToaThuoc>();
        }
    
        public int ID_PhieuKham { get; set; }
        public Nullable<int> ID_LichKham { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string TrieuChung { get; set; }
        public string ChanDoan { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDV> ChiTietDVs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietToaThuoc> ChiTietToaThuocs { get; set; }
        public virtual LichKham LichKham { get; set; }
    }
}
